name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_call:
    outputs:
      version:
        description: "Package version"
        value: ${{ jobs.build.outputs.version }}
      major_version:
        description: "Major version"
        value: ${{ jobs.build.outputs.major_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      major_version: ${{ steps.get_version.outputs.MAJOR_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Prepare CDN files
        run: npm run build:cdn

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Run tests
        run: npm test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            packages/*/dist
            dist
          retention-days: 1
