name: Publish to NPM

on:
  push:
    tags:
      - 'v*' # Déclenche sur les tags qui commencent par 'v'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional)'
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: .

      - name: Get version
        id: get_version
        run: |
          VERSION=${{ needs.build.outputs.version }}
          if [ -z "$VERSION" ]; then
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish @keysako-identity/core
        working-directory: packages/core
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @keysako-identity/react
        working-directory: packages/react
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @keysako-identity/vue
        working-directory: packages/vue
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
